# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoRadioGumb2.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(458, 361)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_velicinaMajice = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.label_velicinaMajice.setFont(font)
        self.label_velicinaMajice.setObjectName("label_velicinaMajice")
        self.verticalLayout.addWidget(self.label_velicinaMajice)
        self.radioButton_M = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.radioButton_M.setFont(font)
        self.radioButton_M.setObjectName("radioButton_M")
        self.buttonGroupVelicinaMajice = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroupVelicinaMajice.setObjectName("buttonGroupVelicinaMajice")
        self.buttonGroupVelicinaMajice.addButton(self.radioButton_M)
        self.verticalLayout.addWidget(self.radioButton_M)
        self.radioButton_L = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.radioButton_L.setFont(font)
        self.radioButton_L.setObjectName("radioButton_L")
        self.buttonGroupVelicinaMajice.addButton(self.radioButton_L)
        self.verticalLayout.addWidget(self.radioButton_L)
        self.radioButton_XL = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.radioButton_XL.setFont(font)
        self.radioButton_XL.setObjectName("radioButton_XL")
        self.buttonGroupVelicinaMajice.addButton(self.radioButton_XL)
        self.verticalLayout.addWidget(self.radioButton_XL)
        self.radioButton_XXL = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.radioButton_XXL.setFont(font)
        self.radioButton_XXL.setObjectName("radioButton_XXL")
        self.buttonGroupVelicinaMajice.addButton(self.radioButton_XXL)
        self.verticalLayout.addWidget(self.radioButton_XXL)
        self.label_NacinPlacanja = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.label_NacinPlacanja.setFont(font)
        self.label_NacinPlacanja.setObjectName("label_NacinPlacanja")
        self.verticalLayout.addWidget(self.label_NacinPlacanja)
        self.radioButton_DebitCreditCard = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.radioButton_DebitCreditCard.setFont(font)
        self.radioButton_DebitCreditCard.setObjectName("radioButton_DebitCreditCard")
        self.buttonGroupNacinPlacanja = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroupNacinPlacanja.setObjectName("buttonGroupNacinPlacanja")
        self.buttonGroupNacinPlacanja.addButton(self.radioButton_DebitCreditCard)
        self.verticalLayout.addWidget(self.radioButton_DebitCreditCard)
        self.radioButton_NetBanking = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.radioButton_NetBanking.setFont(font)
        self.radioButton_NetBanking.setObjectName("radioButton_NetBanking")
        self.buttonGroupNacinPlacanja.addButton(self.radioButton_NetBanking)
        self.verticalLayout.addWidget(self.radioButton_NetBanking)
        self.radioButton_CashOnDelivery = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.radioButton_CashOnDelivery.setFont(font)
        self.radioButton_CashOnDelivery.setObjectName("radioButton_CashOnDelivery")
        self.buttonGroupNacinPlacanja.addButton(self.radioButton_CashOnDelivery)
        self.verticalLayout.addWidget(self.radioButton_CashOnDelivery)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_velicinaMajice.setText(_translate("Dialog", "Odaberite veličinu majice"))
        self.radioButton_M.setText(_translate("Dialog", "M"))
        self.radioButton_L.setText(_translate("Dialog", "L"))
        self.radioButton_XL.setText(_translate("Dialog", "XL"))
        self.radioButton_XXL.setText(_translate("Dialog", "XXL"))
        self.label_NacinPlacanja.setText(_translate("Dialog", "Odaberite način plačanja"))
        self.radioButton_DebitCreditCard.setText(_translate("Dialog", "DEbit/Credit Card"))
        self.radioButton_NetBanking.setText(_translate("Dialog", "NetBanking"))
        self.radioButton_CashOnDelivery.setText(_translate("Dialog", "Cash On Delivery"))
