# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ucitajRadnika.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UcitajRadnika(object):
    def setupUi(self, UcitajRadnika):
        UcitajRadnika.setObjectName("UcitajRadnika")
        UcitajRadnika.resize(367, 494)
        self.verticalLayout = QtWidgets.QVBoxLayout(UcitajRadnika)
        self.verticalLayout.setObjectName("verticalLayout")
        self.naziv = QtWidgets.QLabel(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(24)
        self.naziv.setFont(font)
        self.naziv.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.naziv.setAlignment(QtCore.Qt.AlignCenter)
        self.naziv.setObjectName("naziv")
        self.verticalLayout.addWidget(self.naziv)
        self.dodajSliku = QtWidgets.QLabel(UcitajRadnika)
        self.dodajSliku.setText("")
        self.dodajSliku.setPixmap(QtGui.QPixmap("slike/person-male.png"))
        self.dodajSliku.setAlignment(QtCore.Qt.AlignCenter)
        self.dodajSliku.setObjectName("dodajSliku")
        self.verticalLayout.addWidget(self.dodajSliku)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.imeLabel = QtWidgets.QLabel(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.imeLabel.setFont(font)
        self.imeLabel.setObjectName("imeLabel")
        self.gridLayout.addWidget(self.imeLabel, 0, 0, 1, 1)
        self.lineEditIme = QtWidgets.QLineEdit(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEditIme.setFont(font)
        self.lineEditIme.setObjectName("lineEditIme")
        self.gridLayout.addWidget(self.lineEditIme, 0, 1, 1, 1)
        self.prezimeLabel = QtWidgets.QLabel(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.prezimeLabel.setFont(font)
        self.prezimeLabel.setObjectName("prezimeLabel")
        self.gridLayout.addWidget(self.prezimeLabel, 1, 0, 1, 1)
        self.lineEditPrezime = QtWidgets.QLineEdit(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEditPrezime.setFont(font)
        self.lineEditPrezime.setObjectName("lineEditPrezime")
        self.gridLayout.addWidget(self.lineEditPrezime, 1, 1, 1, 1)
        self.telefonLabel = QtWidgets.QLabel(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.telefonLabel.setFont(font)
        self.telefonLabel.setObjectName("telefonLabel")
        self.gridLayout.addWidget(self.telefonLabel, 2, 0, 1, 1)
        self.lineEditTelefon = QtWidgets.QLineEdit(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEditTelefon.setFont(font)
        self.lineEditTelefon.setObjectName("lineEditTelefon")
        self.gridLayout.addWidget(self.lineEditTelefon, 2, 1, 1, 1)
        self.emailLabel = QtWidgets.QLabel(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.gridLayout.addWidget(self.emailLabel, 3, 0, 1, 1)
        self.lineEditEmail = QtWidgets.QLineEdit(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.gridLayout.addWidget(self.lineEditEmail, 3, 1, 1, 1)
        self.slikaLabel = QtWidgets.QLabel(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.slikaLabel.setFont(font)
        self.slikaLabel.setObjectName("slikaLabel")
        self.gridLayout.addWidget(self.slikaLabel, 4, 0, 1, 1)
        self.btnPretraziSliku = QtWidgets.QPushButton(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnPretraziSliku.setFont(font)
        self.btnPretraziSliku.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btnPretraziSliku.setObjectName("btnPretraziSliku")
        self.gridLayout.addWidget(self.btnPretraziSliku, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.adresaLabel = QtWidgets.QLabel(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.adresaLabel.setFont(font)
        self.adresaLabel.setObjectName("adresaLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.adresaLabel)
        self.textEditAdresa = QtWidgets.QTextEdit(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textEditAdresa.setFont(font)
        self.textEditAdresa.setObjectName("textEditAdresa")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEditAdresa)
        self.btnDodaj = QtWidgets.QPushButton(UcitajRadnika)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnDodaj.setFont(font)
        self.btnDodaj.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.btnDodaj.setObjectName("btnDodaj")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btnDodaj)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(UcitajRadnika)
        QtCore.QMetaObject.connectSlotsByName(UcitajRadnika)

    def retranslateUi(self, UcitajRadnika):
        _translate = QtCore.QCoreApplication.translate
        UcitajRadnika.setWindowTitle(_translate("UcitajRadnika", "Ucitaj Radnika"))
        self.naziv.setText(_translate("UcitajRadnika", "Učitaj radnika"))
        self.imeLabel.setText(_translate("UcitajRadnika", "Ime :"))
        self.lineEditIme.setPlaceholderText(_translate("UcitajRadnika", "Unesi ime radnika"))
        self.prezimeLabel.setText(_translate("UcitajRadnika", "Prezime:"))
        self.lineEditPrezime.setPlaceholderText(_translate("UcitajRadnika", "Unesi prezime radnika"))
        self.telefonLabel.setText(_translate("UcitajRadnika", "Telefon :"))
        self.lineEditTelefon.setPlaceholderText(_translate("UcitajRadnika", "Unesi broj telefona radnika"))
        self.emailLabel.setText(_translate("UcitajRadnika", "Email:"))
        self.lineEditEmail.setPlaceholderText(_translate("UcitajRadnika", "Unesi email radnika"))
        self.slikaLabel.setText(_translate("UcitajRadnika", "Slika :"))
        self.btnPretraziSliku.setText(_translate("UcitajRadnika", "Pretraži"))
        self.adresaLabel.setText(_translate("UcitajRadnika", "Adresa :"))
        self.btnDodaj.setText(_translate("UcitajRadnika", "Učitaj"))
